// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFhVWWKVpH1a9SOZJEUGfNh_V3U3z723k',
    appId: '1:996603799042:web:70dfb4b439030879f7a91b',
    messagingSenderId: '996603799042',
    projectId: 'homespot-77ba6',
    authDomain: 'homespot-77ba6.firebaseapp.com',
    databaseURL: 'https://homespot-77ba6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homespot-77ba6.firebasestorage.app',
    measurementId: 'G-9PZW93GX5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0IZuItxVBVw_jIOzXiyHsvQFViwvLLhU',
    appId: '1:996603799042:android:64fd84c4d283d070f7a91b',
    messagingSenderId: '996603799042',
    projectId: 'homespot-77ba6',
    databaseURL: 'https://homespot-77ba6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homespot-77ba6.firebasestorage.app',
  );
}
